---

- name: Clone repo.
  git:
    repo=git@github.com:drush-ops/drush.git
    dest=~/Projects/drush
    remote=drush-ops
    update=no

- name: Add remote for personal fork.
  shell: git remote add me git@github.com:TravisCarden/drush.git
  args:
    chdir: ~/Projects/drush
  register: result
  changed_when: result.rc != 128
  failed_when: false

- name: Configure user email.
  git_config: name=user.email repo=~/Projects/drush scope=local value=travis.carden@gmail.com

- name: Install Composer packages.
  composer:
    command: install
    # @todo Figure out how to make this a relative path.
    working_dir: /Users/travis.carden/Projects/drush

- name: Symlink executable.
  file:
    src: ~/Projects/drush/drush
    path: /usr/local/bin/drush
    state: link
