---

- name: Tap Homebrew repositories.
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/versions
    - homebrew/homebrew-php
    - homebrew/completions
    - homebrew/versions

- name: Install Homebrew packages.
  homebrew: name={{ item }} state=present
  with_items:
    - bash-completion
    - chromedriver
    - composer
    - composer-completion
    - dos2unix
    - git
    - mas
    - node4-lts
    - npm
    - nvm
    - php56
    - the_silver_searcher
    - ruby
    - wget

- name: Install Homebrew Casks.
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - adium
    - alfred
    - anybar
    - appcleaner
    - atom
    - bartender
    - calibre
    - dropbox
    - evernote
    - fantastical
    - firefox
    - fliqlo
    - flux
    - google-chrome
    - hipchat
    - hyperswitch
    - imageoptim
    - iterm2
    - java
    - keepassx
    - kindle
    - logitech-control-center
    - macpaw-gemini
    - phpstorm
    - sequel-pro
    - skype
    - slack
    - snagit3
    - spectacle
    - timer
    - toggldesktop
    - vagrant
    - virtualbox
    - viscosity
    - zoomus
