---

- name: Tap Homebrew repositories.
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/drivers
    - caskroom/versions
    - homebrew/homebrew-php

- name: Install Homebrew packages.
  homebrew: name={{ item }} state=present
  with_items:
    - ansible
    - bash-completion
    - composer
    - dos2unix
    - git
    - gpatch # https://docs.acquia.com/article/fixing-failing-composer-patches-updating-gnu-patch
    - graphviz
    - hub
    - mas
    - php71
    - php71-xdebug
    - the_silver_searcher
    - ruby
    - tldr
    - tree
    - wget

- name: Install Homebrew Casks.
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - alfred
    - android-file-transfer
    - appcleaner
    - atext
    - atom
    - bartender
    - cacher
    - calibre
    - cocktail
    - db-browser-for-sqlite
    - diffmerge
    - dropbox
    - dynalist
    - evernote
    - firefox
    - firefox-developer-edition
    - fliqlo
    - fluid
    - gemini-classic
    - google-chrome
    - imageoptim
    - iterm2
    - java
    - jetbrains-toolbox
    - kindle
    - logitech-control-center
    - logitech-options
    - macx-dvd-ripper-mac-free-edition
    - mailplane
    - muzzle
    - netgeargenie
    - numi
    - omnifocus
    - overdrive-media-console
    - postman
    - sequel-pro
    - skype
    - slack
    - snagit3
    - spectacle
    - stay
    - timer
    - toggl
    - ubar
    - vagrant
    - virtualbox
    - viscosity
    - vlc
    - xee
    - xmind
    - zoomus
