---

- name: Tap Homebrew repositories.
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask-drivers

- name: Install Homebrew packages.
  homebrew:
    name:
      - ansible # Automate deployment, configuration, and upgrading
      - bash-completion # Programmable completion for Bash 3.2
      - composer # Dependency Manager for PHP
      - dos2unix # Convert text between DOS, UNIX, and Mac formats
      - git # Distributed revision control system
      - git-flow # Extensions to follow Vincent Driessen's branching model
      - gpatch # Apply a diff file to an original
      - graphviz # Graph visualization software from AT&T and Bell Labs
      - httpie # User-friendly cURL replacement (command-line HTTP client)
      - hub # Add GitHub support to git on the command-line
      - mas # Mac App Store command-line interface
      - node # Platform built on V8 to build network applications
      - the_silver_searcher # Code-search similar to ack
      - ruby # Powerful, clean, object-oriented scripting language
      - sqlite # Command-line interface for SQLite
      - terminal-notifier # Send macOS User Notifications from the command-line
      - tldr # Simplified and community-driven man pages
      - tree # Display directories as trees (with optional color/HTML output)
      - wget # Internet file retriever
      # phpenv dependencies:
      - bison # Parser generator
      - libxml2 # GNOME XML library
      - openssl # SSL/TLS cryptography library
      - re2c # Generate C-based recognizers from regular expressions
      - zlib # General-purpose lossless data-compression library
    state: present

- name: Install Homebrew Casks.
  homebrew_cask: name={{ item }} state=present
  with_items:
    - alfred # https://www.alfredapp.com/
    - android-file-transfer # https://www.android.com/filetransfer/
    - anylist # https://www.anylistapp.com/
    - appcleaner # https://freemacsoft.net/appcleaner/
    - atom # https://atom.io/
    - bartender # https://www.macbartender.com/
    - calibre # https://calibre-ebook.com/
    - cocktail # https://www.maintain.se/cocktail/
    - daisydisk # https://daisydiskapp.com/
    - db-browser-for-sqlite # http://sqlitebrowser.org/
    - diffmerge # https://www.sourcegear.com/diffmerge/
    - drawio # https://www.draw.io/
    - dropbox # https://www.dropbox.com/
    - dynalist # https://dynalist.io/
    - eaglefiler # https://c-command.com/eaglefiler/
    - evernote # https://evernote.com/
    - firefox-developer-edition # https://www.mozilla.org/firefox/developer/
    - fliqlo # https://fliqlo.com/
    - fluid # http://fluidapp.com/
    - gemini-classic # https://macpaw.com/gemini-classic
    - goodsync # https://www.goodsync.com/
    - google-chrome # https://www.google.com/chrome/
    - imageoptim # https://imageoptim.com/mac
    - istat-menus # https://bjango.com/mac/istatmenus/
    - iterm2 # https://www.iterm2.com/
    - java # https://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html
    - jetbrains-toolbox # https://www.jetbrains.com/toolbox/app/
    - kindle # https://www.amazon.com/gp/digital/fiona/kcp-landing-page
    - logitech-control-center # https://support.logitech.com/en_us/product/3129
    # - logitech-options # https://support.logitech.com/en_us/software/options
    - macmediakeyforwarder # http://milgra.com/mac-media-key-forwarder.html
    - mailplane # https://mailplaneapp.com/
    - mutespotifyads # https://github.com/simonmeusel/MuteSpotifyAds
    - muzzle # https://muzzleapp.com/
    - overdrive-media-console # https://www.overdrive.com/
    - postman # https://www.getpostman.com/
    - sequel-pro # https://www.sequelpro.com/
    - slack # https://slack.com/
    - soulver # http://www.acqualia.com/soulver/
    - spectacle # https://www.spectacleapp.com/
    - spotify # https://www.spotify.com/
    - spotmenu # https://github.com/kmikiy/SpotMenu
    - stay # https://cordlessdog.com/stay/
    - timer # https://www.apimac.com/mac/timer/
    - ubar # https://brawersoftware.com/products/ubar
    - vagrant # https://www.vagrantup.com/
    - virtualbox # https://www.virtualbox.org/
    - viscosity # https://www.sparklabs.com/viscosity/
    - vlc # https://www.videolan.org/vlc/
    - xee # https://theunarchiver.com/xee
    - xmind # https://www.xmind.net/
