---

- name: Tap Homebrew repositories.
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask-drivers

- name: Install Homebrew packages.
  homebrew:
    name:
      - ansible # Automate deployment, configuration, and upgrading
      - composer # Dependency Manager for PHP
      - git # Distributed revision control system
      - git-flow # Extensions to follow Vincent Driessen's branching model
      - gpatch # Apply a diff file to an original
      - hub # Add GitHub support to git on the command-line
      - mas # Mac App Store command-line interface
      - the_silver_searcher # Code-search similar to ack
      - sqlite # Command-line interface for SQLite
      - tldr # Simplified and community-driven man pages
      - tree # Display directories as trees (with optional color/HTML output)
      - wget # Internet file retriever
    state: present

- name: Install Homebrew Casks.
  homebrew_cask: name={{ item }} state=present
  with_items:
    - airtable # https://airtable.com/
    - alfred # https://www.alfredapp.com/
    - anylist # https://www.anylistapp.com/
    - appcleaner # https://freemacsoft.net/appcleaner/
    - atom # https://atom.io/
    - bartender # https://www.macbartender.com/
    - brave-browser # https://brave.com/
    - beekeeper-studio # https://www.beekeeperstudio.io/
    - diffmerge # https://www.sourcegear.com/diffmerge/
    - dupeguru # https://dupeguru.voltaicideas.net/
    - dynalist # https://dynalist.io/
    - evernote # https://evernote.com/
    - find-any-file # https://apps.tempel.org/FindAnyFile/
    - finicky # https://github.com/johnste/finicky
    - firefox # https://www.mozilla.org/firefox/
    - fliqlo # https://fliqlo.com/
    - fluid # http://fluidapp.com/
    - google-backup-and-sync # https://www.google.com/drive/download/
    - google-chrome # https://www.google.com/chrome/
    - gpg-suite # https://gpgtools.org/
    - imageoptim # https://imageoptim.com/mac
    - istat-menus # https://bjango.com/mac/istatmenus/
    - iterm2 # https://www.iterm2.com/
    - java # https://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html
    - jetbrains-toolbox # https://www.jetbrains.com/toolbox/app/
    - macmediakeyforwarder # http://milgra.com/mac-media-key-forwarder.html
    - mailplane # https://mailplaneapp.com/
    - meetingbar # https://github.com/leits/MeetingBar
    - mutespotifyads # https://github.com/simonmeusel/MuteSpotifyAds
    - muzzle # https://muzzleapp.com/
    - nordvpn # https://nordvpn.com/
    - qview # https://github.com/jurplel/qView
    - rcdefaultapp # http://www.rubicode.com/Software/RCDefaultApp/
    - slack # https://slack.com/
    - soulver2 # https://www.acqualia.com/soulver/
    - spectacle # https://www.spectacleapp.com/
    - spotify # https://www.spotify.com/
    - stay # https://cordlessdog.com/stay/
    - typora # https://typora.io/
    - ubar # https://brawersoftware.com/products/ubar
    - xmind # https://www.xmind.net/
