---

- name: Tap Homebrew repositories.
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/drivers
    - caskroom/versions
    - homebrew/homebrew-php
    - homebrew/completions
    - homebrew/versions

- name: Install Homebrew packages.
  homebrew: name={{ item }} state=present
  with_items:
    - ansible
    - bash-completion
    - composer
    - dos2unix
    - git
    - hub
    - mas
    - node4-lts
    - npm
    - nvm
    - php71
    - php71-xdebug
    - the_silver_searcher
    - ruby
    - tldr
    - tree
    - wget

- name: Install Homebrew Casks.
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - alfred
    - appcleaner
    - atext
    - atom
    - bartender
    - cacher
    - calibre
    - db-browser-for-sqlite
    - diffmerge
    - dropbox
    - dynalist
    - evernote
    - firefox
    - fliqlo
    - fluid
    - gemini
    - google-chrome
    - imageoptim
    - integrity
    - iterm2
    - java
    - jetbrains-toolbox
    - kindle
    - logitech-control-center
    - mailplane
    - netgeargenie
    - nocturne
    - omnifocus
    - overdrive-media-console
    - sequel-pro
    - skype
    - slack
    - snagit3
    - spectacle
    - timer
    - toggl
    - ubar
    - vagrant
    - virtualbox
    - viscosity
    - vlc
    - xee
    - xmind
    - zoomus
