---

- name: Install Mac App Store apps.
  shell: mas list | grep {{ item }} || mas install {{ item }}
  with_items:
    - 937984704 # Amphetamine
    - 1287239339 # ColorSlurp
    - 975937182 # Fantastical 2 - Calendar and Reminders
    - 1346203938 # OmniFocus
    - 1289583905 # Pixelmator Pro
    - 504700302 # PDF Squeezer
    - 880001334 # Reeder
    - 496437906 # Shush
    - 425424353 # The Unarchiver
    - 497799835 # Xcode
    - 1510445899 # Meeter for Zoom, Teams & Co
  register: result
  changed_when: result.stdout.find('Installed') != -1
