---

- name: Install Mac App Store apps.
  shell: mas list | grep {{ item }} || mas install {{ item }}
  with_items:
    - 937984704 # Amphetamine
    - 472790630 # Bible Study
    - 1024917449 # Cloud Outliner Pro
    - 506189836 # Harvest
    - 489690915 # My Medical
    - 407963104 # Pixelmator
    - 425424353 # The Unarchiver
  register: result
  changed_when: result.stdout.find('Installed') != -1
