---

- name: Upgrade outdated apps from the Mac App Store.
  shell: mas upgrade
  register: result
  changed_when: result.stdout.find('Everything is up-to-date') != 0

- name: Install Mac App Store apps.
  shell: mas list | grep {{ item }} || mas install {{ item }}
  with_items:
    - 937984704 # Amphetamine
    - 472790630 # Bible Study
    - 1394863440 # Banktivity 7
    - 975937182 # Fantastical 2 - Calendar and Reminders
    - 506189836 # Harvest
    - 489690915 # My Medical
    - 547818064 # myPoint Shade
    - 1346203938 # OmniFocus
    - 1303222628 # Paprika Recipe Manager 3
    - 407963104 # Pixelmator
    - 504700302 # PDF Squeezer
    - 880001334 # Reeder
    - 496437906 # Shush
    - 425424353 # The Unarchiver
    - 410628904 # Wunderlist
    - 497799835 # Xcode
  register: result
  changed_when: result.stdout.find('Installed') != -1
