---

- name: Install Mac App Store apps.
  shell: mas list | grep {{ item }} || mas install {{ item }}
  with_items:
    - 489690915 # My Medical
    - 407963104 # Pixelmator
  register: result
  changed_when: result.stdout.find('Installed') != -1
