---

- hosts: localhost
  connection: local
  tasks:
  - include_tasks: tasks/{{ file }}.yml
    with_items:
    - homebrew
    - gems
    - drush
    - mac-app-store
    loop_control:
      loop_var: file
